;; ---------------
;; Autogenerated customization stuff
;; ---------------
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ccls-args
   (quote
    ("--log-file=/tmp/ccls.log" "-v=1" "--init={\"compilationDatabaseDirectory\": \"build\"}")))
 '(comment-padding "*  ")
 '(custom-safe-themes
   (quote
    ("9d54f3a9cf99c3ffb6ac8e84a89e8ed9b8008286a81ef1dbd48d24ec84efb2f1" "a4fa3280ffa1f2083c5d4dab44a7207f3f7bcb76e720d304bd3bd640f37b4bef" "de43de35da390617a5b3e39b6b27c107cc51271eb95cceb1f43d13d9647c911d" "fe76f3d5094967034192f6a505085db8db6deb0e135749d9a54dc488d6d3ee2f" default)))
 '(dark-mode t)
 '(light-mode nil)
 '(magit-commit-arguments (quote ("-S")))
 '(org-agenda-files
   (quote
    ("/home/evan/Sync/notes/automation.org" "/home/evan/Sync/notes/general.org" "/home/evan/Sync/school/current/19au/MATH308/math308.org" "/home/evan/Sync/school/current/19au/MUS120/notes/9-25-19.org" "/home/evan/Sync/school/current/19au/MUS120/music120.org" "/home/evan/Sync/school/current/19au/PHYS122/notes/9-25-19.org" "/home/evan/Sync/school/current/19au/PHYS122/phys122.org")))
 '(package-selected-packages
   (quote
    (gitpatch gitpatch-send-email emms telega lua-mode dune hydra all-the-icons markdown-mode+ utop ocp-indent merlin-eldoc merlin tuareg yaml-mode groovy-mode go-mode guix slime emojify restclient folding web-mode php-mode company-coq proof-general csv-mode company-arduino arduino-mode flymd impatient-mode web-beautify ein auctex pandoc-mode neotree racket-mode company-quickhelp clang-format ccls cquery column-enforce-mode rainbow-delimiters pdf-tools gradle-mode smartparens geiser yasnippet-snippets yasnippet projectile use-package treemacs lsp-java flycheck lsp-ui company-lsp company lsp-mode magit doom-themes doom-modeline)))
 '(pdf-view-midnight-colors (cons "#0c0a20" "#f2f3f7"))
 '(safe-local-variable-values
   (quote
    ((column-enforce-column 95)
     (geiser-guile-load-path quote
			     ("~/Sync/code/guix"))
     (eval modify-syntax-entry 43 "'")
     (eval modify-syntax-entry 36 "'")
     (eval modify-syntax-entry 126 "'"))))
 '(use-dark-mode t))
 
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
